import { boolean, decodeType, record, string } from "typescript-json-decoder";

export type SlackUser = decodeType<typeof decodeSlackUser>;
export const decodeSlackUser = record({
  id: string,
  team_id: string,
  name: string,
  real_name: string,
  is_bot: boolean,
  is_email_confirmed: boolean,
});

export const samplePayload = {
  id: "U038G4SGK9Q",
  team_id: "TG21XF887",
  name: "zoul_test",
  deleted: false,
  color: "9b3b45",
  real_name: "Tomáš Znamenáček",
  tz: "Europe/Belgrade",
  tz_label: "Central European Time",
  tz_offset: 3600,
  profile: {
    title: "",
    phone: "",
    skype: "",
    real_name: "Tomáš Znamenáček",
    real_name_normalized: "Tomas Znamenacek",
    display_name: "Tomáš Znamenáček",
    display_name_normalized: "Tomas Znamenacek",
    fields: null,
    status_text: "",
    status_emoji: "",
    status_emoji_display_info: [],
    status_expiration: 0,
    avatar_hash: "g64fe32e779a",
    first_name: "Tomáš",
    last_name: "Znamenáček",
    image_24: "https://…24.png",
    image_32: "https://…32.png",
    image_48: "https://…48.png",
    image_72: "https://…72.png",
    image_192: "https://…192.png",
    image_512: "https://…512.png",
    status_text_canonical: "",
    team: "TG21XF887",
  },
  is_admin: false,
  is_owner: false,
  is_primary_owner: false,
  is_restricted: false,
  is_ultra_restricted: false,
  is_bot: false,
  is_app_user: false,
  updated: 1648114412,
  is_email_confirmed: true,
  who_can_share_contact_card: "EVERYONE",
  presence: "away",
};
