/** https://mk.gov.cz/doc/cms_library/priloha-k-zadosti-kod-ciselniku-pf-11464.pdf */
export const ciselnik = [
  {
    "Kód": "121",
    "Název": "Akciová společnost",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "721",
    "Název": "Církve a náboženské společnosti",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "313",
    "Název": "Česká národní banka",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "362",
    "Název": "Česká tisková kancelář",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "771",
    "Název": "Dobrovolný svazek obcí",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "205",
    "Název": "Družstvo",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "722",
    "Název": "Evidované církevní právnické osoby",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "933",
    "Název": "Evropská družstevní společnost",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "932",
    "Název": "Evropská společnost",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "931",
    "Název": "Evropské hospodářské zájmové sdružení",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "941",
    "Název": "Evropské seskupení pro územní spolupráci",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "152",
    "Název": "Garanční fond obchodníků s cennými papíry",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "761",
    "Název": "Honební společenstvo",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "151",
    "Název": "Komoditní burza",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "745",
    "Název": "Komora (hospodářská, agrární)",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "804",
    "Název": "Kraj",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "811",
    "Název": "Městská část, městský obvod",
    "Typ osoby": "právnická osoba *",
    "Platnost od": null,
  },
  {
    "Kód": "921",
    "Název": "Mezinárodní nevládní organizace",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "907",
    "Název": "Mezinárodní odborová organizace",
    "Typ osoby": "právnická osoba",
    "Platnost od": "1.1.2014",
  },
  {
    "Kód": "908",
    "Název": "Mezinárodní organizace zaměstnavatelů",
    "Typ osoby": "právnická osoba",
    "Platnost od": "1.1.2014",
  },
  {
    "Kód": "951",
    "Název":
      "Mezinárodní vojenská organizace vzniklá na základě mezinárodní smlouvy",
    "Typ osoby": "právnická osoba",
    "Platnost od": "1.1.2018",
  },
  {
    "Kód": "117",
    "Název": "Nadace",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "118",
    "Název": "Nadační fond",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "302",
    "Název": "Národní podnik",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "801",
    "Název": "Obec",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "141",
    "Název": "Obecně prospěšná společnost",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "707",
    "Název": "Odborová organizace",
    "Typ osoby": "právnická osoba",
    "Platnost od": "1.11.2017",
  },
  {
    "Kód": "501",
    "Název": "Odštěpný závod",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "425",
    "Název": "Odštěpný závod zahraniční fyzické osoby",
    "Typ osoby": "fyzická osoba",
    "Platnost od": "1.10.2013",
  },
  {
    "Kód": "421",
    "Název": "Odštěpný závod zahraniční právnické osoby",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "708",
    "Název": "Organizace zaměstnavatelů",
    "Typ osoby": "právnická osoba",
    "Platnost od": "1.11.2017",
  },
  {
    "Kód": "922",
    "Název": "Organizační jednotka mezinárodní nevládní organizace",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "734",
    "Název":
      "Organizační jednotka zvláštní organizace pro zastoupení českých zájmů v mezinárodních nevládních organizacích",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "325",
    "Název": "Organizační složka státu",
    "Typ osoby": "právnická osoba *",
    "Platnost od": null,
  },
  {
    "Kód": "423",
    "Název": "Organizační složka zahraniční nadace",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "422",
    "Název": "Organizační složka zahraničního nadačního fondu",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "736",
    "Název": "Pobočný spolek",
    "Typ osoby": "právnická osoba",
    "Platnost od": "1.1.2014",
  },
  {
    "Kód": "100",
    "Název": "Podnikající fyzická osoba tuzemská",
    "Typ osoby": "fyzická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "711",
    "Název": "Politická strana, politické hnutí",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "960",
    "Název":
      "Právnická osoba zřízená zvláštním zákonem zapisovaná do veřejného rejstříku",
    "Typ osoby": "právnická osoba",
    "Platnost od": "1.6.2016",
  },
  {
    "Kód": "331",
    "Název": "Příspěvková organizace zřízená územním samosprávným celkem",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "353",
    "Název": "Rada pro veřejný dohled nad auditem",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "805",
    "Název": "Regionální rada regionu soudržnosti",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "741",
    "Název": "Samosprávná stavovská organizace (profesní komora).",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "521",
    "Název": "Samostatná drobná provozovna (obecního úřadu)",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "145",
    "Název": "Společenství vlastníků jednotek",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "113",
    "Název": "Společnost komanditní",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "112",
    "Název": "Společnost s ručením omezeným",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "706",
    "Název": "Spolek",
    "Typ osoby": "právnická osoba",
    "Platnost od": "1.1.2014",
  },
  {
    "Kód": "352",
    "Název": "Správa železniční dopravní cesty, státní organizace",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "326",
    "Název": "Stálý rozhodčí soud",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "381",
    "Název": "Státní fond ze zákona",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "382",
    "Název": "Státní fond ze zákona nezapisující se do obchodního rejstříku",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "301",
    "Název": "Státní podnik",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "332",
    "Název": "Státní příspěvková organizace",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "723",
    "Název": "Svazy církví a náboženských společností",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "961",
    "Název": "Svěřenský fond",
    "Typ osoby": "právnická osoba *",
    "Platnost od": "1.1.2018",
  },
  {
    "Kód": "641",
    "Název": "Školská právnická osoba",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "161",
    "Název": "Ústav",
    "Typ osoby": "právnická osoba",
    "Platnost od": "1.1.2014",
  },
  {
    "Kód": "111",
    "Název": "Veřejná obchodní společnost",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "661",
    "Název": "Veřejná výzkumná instituce",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "361",
    "Název": "Veřejnoprávní instituce",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "525",
    "Název": "Vnitřní organizační jednotka organizační složky státu",
    "Typ osoby": "právnická osoba *",
    "Platnost od": "1.1.2017",
  },
  {
    "Kód": "392",
    "Název": "Všeobecná zdravotní pojišťovna",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "601",
    "Název": "Vysoká škola (veřejná, státní)",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "424",
    "Název": "Zahraniční fyzická osoba",
    "Typ osoby": "fyzická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "936",
    "Název": "Zahraniční pobočný spolek",
    "Typ osoby": "právnická osoba",
    "Platnost od": "1.1.2014",
  },
  {
    "Kód": "906",
    "Název": "Zahraniční spolek",
    "Typ osoby": "právnická osoba",
    "Platnost od": "1.1.2014",
  },
  {
    "Kód": "962",
    "Název": "Zahraniční svěřenský fond",
    "Typ osoby": "právnická osoba *",
    "Platnost od": "1.1.2018",
  },
  {
    "Kód": "751",
    "Název": "Zájmové sdružení právnických osob",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "426",
    "Název": "Zastoupení zahraniční banky",
    "Typ osoby": "právnická osoba *",
    "Platnost od": "1.9.2017",
  },
  {
    "Kód": "391",
    "Název": "Zdravotní pojišťovna (mimo VZP)",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
  {
    "Kód": "704",
    "Název":
      "Zvláštní organizace pro zastoupení českých zájmů v mezinárodních nevládních organizacích",
    "Typ osoby": "právnická osoba",
    "Platnost od": null,
  },
];

export const nazvyPravnichForem = Object.fromEntries(
  ciselnik.map(({ Kód: code, Název: name }) => [code, name]),
);
