name: Import CRM Data

on:
  schedule:
    - cron: "5 4 * * *" # Run at 4.05 UTC each day
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # Limit running time to one hour max
    env:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      CRM_API_KEY: ${{ secrets.CRM_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Import
        run: |
          npm ci
          ./bin/crm-import.ts
