name: E2E

on:
  push:
    branches: [master, feature/e2e-tests]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn install
      - run: yarn dev
      - run: npx playwright install
      - run: npx playwright test 
