name: Slack Sync

on:
  schedule:
    - cron: "5 2 * * *" # Run at 3.05 UTC each day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_SYNC_TOKEN: ${{ secrets.SLACK_SYNC_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Sync
        run: |
          yarn install
          yarn sync-users
